services:
  db:
    image: postgres:16-alpine
    container_name: hw12_postgres
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME:-hw12_db}
    volumes:
      - hw12_pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-hw12_db}"]
      interval: 2s
      timeout: 3s
      retries: 15

  mailpit:
    image: axllent/mailpit
    container_name: hw12_mailpit
    ports:
      - "8025:8025"
      - "1025:1025"

  redis:
    image: redis:7-alpine
    container_name: hw12_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 3s
      retries: 15

  api:
    build: .
    container_name: hw12_api
    env_file: .env
    environment:
      DB_HOST: db
      MAIL_SERVER: mailpit
      MAIL_PORT: 1025
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      mailpit:
        condition: service_started

volumes:
  hw12_pgdata:
